name: 'issue-translator'
on: 
  issue_comment:
    types: [created]
  issue:
    types: [opened]

jobs:
  build:
    run-on: ubuntu-latest
    steps:
    - uses: usthe/issues-translate-action@v2.7
      with:
        IS_MODIFY_TITLE: false
        CUSTOM_BOT_NOTE: Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
        
      
